# Generated by Django 4.1.3 on 2022-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertasks',
            options={'verbose_name_plural': 'User Tasks Management'},
        ),
        migrations.RenameField(
            model_name='usertasks',
            old_name='taskname',
            new_name='task_name',
        ),
        migrations.AddField(
            model_name='usertasks',
            name='task_description',
            field=models.TextField(default='Default', verbose_name='Task Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertasks',
            name='task_deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
    ]
